# Generated by Django 2.2.1 on 2019-05-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KindService',
            fields=[
                ('Id_KindService', models.AutoField(primary_key=True, serialize=False)),
                ('Name_work', models.CharField(max_length=255)),
                ('Cifer_service', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kindservice',
            },
        ),
    ]
