# Generated by Django 2.2.1 on 2019-05-10 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('Id_creator', models.AutoField(primary_key=True, serialize=False)),
                ('Name_creator', models.CharField(max_length=255)),
                ('Cifer_creator', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'creator',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Id_Employee', models.AutoField(primary_key=True, serialize=False)),
                ('FIO', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='KindDetail',
            fields=[
                ('Id_KindDetail', models.AutoField(primary_key=True, serialize=False)),
                ('Name_Detail', models.CharField(max_length=255)),
                ('Cifer_kind', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kinddetail',
            },
        ),
        migrations.CreateModel(
            name='KindDevice',
            fields=[
                ('Id_KindDevice', models.AutoField(primary_key=True, serialize=False)),
                ('NameDevice', models.CharField(max_length=255)),
                ('Cifer_kind', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kinddevice',
            },
        ),
        migrations.CreateModel(
            name='KindService',
            fields=[
                ('Id_KindService', models.AutoField(primary_key=True, serialize=False)),
                ('Name_work', models.CharField(max_length=255)),
                ('Cifer_service', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kindservice',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('Id_Master', models.AutoField(primary_key=True, serialize=False)),
                ('FIO', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('Id_Status', models.AutoField(primary_key=True, serialize=False)),
                ('NameStatus', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Type_payment',
            fields=[
                ('ID_type', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_payment',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('Id_device', models.AutoField(primary_key=True, serialize=False)),
                ('Model_device', models.CharField(max_length=255)),
                ('IMEI', models.CharField(max_length=255)),
                ('Id_KindDevice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.KindDevice')),
                ('Id_creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Creator')),
            ],
            options={
                'db_table': 'device',
            },
        ),
    ]
