# Generated by Django 2.2.1 on 2019-05-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_komraz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindDetail',
            fields=[
                ('Id_KindDetail', models.AutoField(primary_key=True, serialize=False)),
                ('Name_Detail', models.CharField(max_length=255)),
                ('Cifer_kind', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kinddetail',
            },
        ),
    ]
