# Generated by Django 2.2.1 on 2019-05-10 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top_komraz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('Id_contract', models.AutoField(primary_key=True, serialize=False)),
                ('ConclusionDate', models.DateField()),
                ('PeriodExecute', models.DateField()),
                ('Defect', models.CharField(max_length=255)),
                ('Appearance', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'contract',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('FIO', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=50)),
                ('Adress', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('ID_Provider', models.AutoField(primary_key=True, serialize=False)),
                ('Organization_name', models.CharField(max_length=255)),
                ('Organisation_Adress', models.CharField(max_length=255)),
                ('Organisation_phone', models.CharField(max_length=50)),
                ('Employee', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('IdService', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.CharField(max_length=255)),
                ('Id_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.KindService')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Request_delivery',
            fields=[
                ('ID_request', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('ID_Provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Provider')),
            ],
            options={
                'db_table': 'request_delivery',
            },
        ),
        migrations.CreateModel(
            name='Orderentity',
            fields=[
                ('ID_Order', models.AutoField(primary_key=True, serialize=False)),
                ('Id_Master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Master')),
                ('Id_Status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Status')),
                ('Id_contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Contract')),
            ],
            options={
                'db_table': 'orderentity',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('Id_Detail', models.AutoField(primary_key=True, serialize=False)),
                ('NameDetail', models.CharField(max_length=255)),
                ('PriceDetail', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ID_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Request_delivery')),
                ('Id_KindDetail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.KindDetail')),
            ],
            options={
                'db_table': 'detail',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='ID_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Service'),
        ),
        migrations.AddField(
            model_name='contract',
            name='Id_Employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Employee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='Id_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='Id_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Device'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('ID_certificate', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Guarantee', models.CharField(max_length=255)),
                ('Sum', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ID_Order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Orderentity')),
                ('ID_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Type_payment')),
            ],
            options={
                'db_table': 'certificate',
            },
        ),
    ]
