# Generated by Django 2.2.1 on 2019-05-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_komraz', '0002_kinddetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindDevice',
            fields=[
                ('Id_KindDevice', models.AutoField(primary_key=True, serialize=False)),
                ('NameDevice', models.CharField(max_length=255)),
                ('Cifer_kind', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kinddevice',
            },
        ),
    ]
