# Generated by Django 2.2.1 on 2019-05-12 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top_komraz', '0002_auto_20190510_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_fix',
            fields=[
                ('ID_certificate', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Guarantee', models.CharField(max_length=255)),
                ('Sum', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'certificate_fix',
            },
        ),
        migrations.CreateModel(
            name='Contract_fix',
            fields=[
                ('Id_contract', models.AutoField(primary_key=True, serialize=False)),
                ('ConclusionDate', models.DateField()),
                ('PeriodExecute', models.DateField()),
                ('Defect', models.CharField(max_length=255)),
                ('Appearance', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'contract_fix',
            },
        ),
        migrations.CreateModel(
            name='Detail_fix',
            fields=[
                ('Id_Detail', models.AutoField(primary_key=True, serialize=False)),
                ('NameDetail', models.CharField(max_length=255)),
                ('PriceDetail', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Number', models.IntegerField()),
                ('ID_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Request_delivery')),
                ('Id_KindDetail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.KindDetail')),
            ],
            options={
                'db_table': 'detail_fix',
            },
        ),
        migrations.CreateModel(
            name='Orderentity_fix',
            fields=[
                ('ID_Order', models.AutoField(primary_key=True, serialize=False)),
                ('Id_Master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Master')),
                ('Id_Status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Status')),
                ('Id_contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Contract_fix')),
            ],
            options={
                'db_table': 'orderentity_fix',
            },
        ),
        migrations.RemoveField(
            model_name='contract',
            name='ID_service',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='Id_Employee',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='Id_customer',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='Id_device',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='ID_request',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='Id_KindDetail',
        ),
        migrations.RemoveField(
            model_name='orderentity',
            name='Id_Master',
        ),
        migrations.RemoveField(
            model_name='orderentity',
            name='Id_Status',
        ),
        migrations.RemoveField(
            model_name='orderentity',
            name='Id_contract',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='Orderentity',
        ),
        migrations.AddField(
            model_name='contract_fix',
            name='ID_Detail_fix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Detail_fix'),
        ),
        migrations.AddField(
            model_name='contract_fix',
            name='ID_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Service'),
        ),
        migrations.AddField(
            model_name='contract_fix',
            name='Id_Employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Employee'),
        ),
        migrations.AddField(
            model_name='contract_fix',
            name='Id_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Customer'),
        ),
        migrations.AddField(
            model_name='contract_fix',
            name='Id_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Device'),
        ),
        migrations.AddField(
            model_name='certificate_fix',
            name='ID_Order_fix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Orderentity_fix'),
        ),
        migrations.AddField(
            model_name='certificate_fix',
            name='ID_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Type_payment'),
        ),
    ]
