# Generated by Django 2.2.1 on 2019-05-13 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top_komraz', '0004_auto_20190512_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_delivery3',
            fields=[
                ('ID_request', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Quantity', models.IntegerField()),
                ('ID_Detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Detail_fix2')),
                ('ID_Provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Provider')),
            ],
            options={
                'db_table': 'request_delivery3',
            },
        ),
        migrations.DeleteModel(
            name='Request_delivery2',
        ),
    ]
