# Generated by Django 2.2.1 on 2019-05-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top_komraz', '0005_auto_20190513_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implemented',
            fields=[
                ('ID_certificate', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('ID_Detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Detail_fix2')),
            ],
            options={
                'db_table': 'implemented',
            },
        ),
    ]
