# Generated by Django 2.2.1 on 2019-05-13 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top_komraz', '0007_period_plan_procurement_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('Id_Employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Employee')),
                ('Id_Master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Master')),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Procurement_plan1',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Quantity', models.IntegerField()),
                ('Id_Employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Employee')),
                ('id_period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Period')),
            ],
            options={
                'db_table': 'procurement_plan1',
            },
        ),
        migrations.DeleteModel(
            name='Procurement_plan',
        ),
    ]
