# Generated by Django 2.2.1 on 2019-05-13 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top_komraz', '0008_auto_20190514_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login1',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('Id_Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Employee')),
                ('Id_Master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='top_komraz.Master')),
            ],
            options={
                'db_table': 'login1',
            },
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
